name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-pdm
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pdm install -G:all

      - name: Ruff
        run: pdm run ruff check .

      - name: Mypy
        run: pdm run mypy src

      - name: Pytest
        run: pdm run pytest
